default world adapter {
	export producer: pkg.producer
	export consumer: pkg.consumer
	
	import downstream: pkg.handler

	// handler exported for host guest_call
	export handler: pkg.handler

    import host: pkg.wasmcloud.host
    export actor: pkg.wasmcloud.actor
}