/// An interface for a consumer relying on push-based message delivery.
default interface handler {
    use pkg.types.{event, error}

	/// Creates an on-receive handler push-based message delivery.
  	on-receive: func(e: event) -> result<_, error>
}