default world messaging-capability-provider {
	export producer: pkg.producer
	export consumer: pkg.consumer

  // messaging rpc types
  import wasmcloud-messaging: pkg.wasmcloud-messaging.wasmcloud-messaging

	// handler exported for host guest_call
	export handler: pkg.handler

}