
interface host {
    host-call: func(binding: string, namespace: string, operation: string, payload: list<u8>) -> result<list<u8>, string>
}
 
interface actor {
    guest-call: func(operation: string, payload: list<u8>) -> result<list<u8>, string>
    wasmbus-rpc-version: func() -> u32
}
