# This is a full manifest of the petclinic example. Using this example requires you to
# have WADM running: https://github.com/wasmCloud/wadm.
#
# Please note that the connection URI in this manifest is insecure for ease-of-use, and
# should not be used in a production scenario.
# You can deploy this example with a simple command: `wash app deploy wadm.yaml`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: petclinic
  annotations:
    version: v0.0.1
    description: "wasmCloud Pet Clinic Sample"
spec:
  components:
    - name: ui
      type: actor
      properties:
        image: wasmcloud.azurecr.io/ui:0.3.2
      traits:
        - type: spreadscaler
          properties:
            replicas: 1

    - name: customers
      type: actor
      properties:
        image: wasmcloud.azurecr.io/customers:0.3.1
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: postgres
            values:
              uri: postgres://petclinic:supersecret123@127.0.0.1:5432/petclinic

    - name: vets
      type: actor
      properties:
        image: wasmcloud.azurecr.io/vets:0.3.1
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: postgres
            values:
              uri: postgres://petclinic:supersecret123@127.0.0.1:5432/petclinic

    - name: visits
      type: actor
      properties:
        image: wasmcloud.azurecr.io/visits:0.3.1
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: postgres
            values:
              uri: postgres://petclinic:supersecret123@127.0.0.1:5432/petclinic

    - name: clinicapi
      type: actor
      properties:
        image: wasmcloud.azurecr.io/clinicapi:0.3.1
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
            values:
              address: 0.0.0.0:8080

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.16.3
        contract: wasmcloud:httpserver
    - name: postgres
      type: capability
      properties:
        image: wasmcloud.azurecr.io/sqldb-postgres:0.3.4
        contract: wasmcloud:sqldb
