# codegen.toml

[[models]]
path = "../../../interfaces/core"
files = [ "wasmcloud-model.smithy", "wasmcloud-core.smithy"  ]

[[models]]
path = "."
files = [ "union-demo.smithy", "smithy-types.smithy" ]


[rust]
output_dir = "rust"
files = [ 
  { path = "src/union_demo.rs", namespace = "org.wasmcloud.example.union_demo" },
  { path = "src/smithy_types.rs", namespace = "org.wasmcloud.example.smithy_types" },
]

[assemblyscript]
output_dir = "asm"
files = [ 
  { path = "src/union_demo.asm", namespace = "org.wasmcloud.example.union_demo" },
  { path = "src/smithy_types.asm", namespace = "org.wasmcloud.example.smithy_types" },
]

#[tinygo]
#output_dir = "tinygo"
#files = [
#  { path = "src/union_demo.go", namespace = "org.wasmcloud.example.union_demo" },
#  { path = "src/smithy_types.go", namespace = "org.wasmcloud.example.smithy_types" },
#]
