# cron Makefile

CAPABILITY_ID = "wasmcloud:example:cron"
NAME = "Cron Provider"
VENDOR = "wasmCloud"
PROJECT = cron
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

