name = "KVCounter"
language = "rust"
type = "actor"

[actor]
claims = ["wasmcloud:httpserver", "wasmcloud:keyvalue"]
wasm_target = "wasm32-wasi-preview2"
wit_world = "kvcounter"
# The adapter file in this folder is v12.0.2 adapter of wasmtime:
#
# https://github.com/bytecodealliance/wasmtime/releases/tag/v12.0.2
#
# Since upstream projects have moved past this adapter, we use the local
# version here to ensure the demo keeps working as WASI and WIT definitions
# change and improve
wasi_preview2_adapter_path = "wasi_snapshot_preview1.wasm"