# This docker-compose file loads 
#   nats with JetStream enabled
#   a local OCI registry
#   redis (for the kvredis capability provider)
#   grafana + tempo for tracing

version: "3"
services:
  nats:
    image: nats:2.3
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    command: [ "-js" ]
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  registry:
    image: registry:2.7
    ports:
      - "5000:5000"
  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - 5050:3000
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - tempo  
  tempo:
    image: grafana/tempo:1.1.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 8000:8000 # tempo
      - 55681:55681 # otlp http  
  wadm:
    depends_on:
      - "nats"
      - "redis"
    image: wasmcloud.azurecr.io/wadm:0.1.0
    environment:
      - WADM_NATS_HOST=nats
      - WADM_REDIS_HOST=redis
