[package]
name = "dogs-and-cats"
version = "0.2.0"
authors = [ "wasmCloud Team" ]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "dogs_and_cats"

[dependencies]
futures = "0.3"
serde_json = "1.0.81"
wasmbus-rpc = "0.9"
wasmcloud-interface-numbergen = "0.6"
wasmcloud-interface-logging = "0.6"
wasmcloud-interface-httpserver = "0.6"
wasmcloud-interface-httpclient = "0.6"

[profile.release]
# Optimize for small code size
lto = true
# Strip debug symbols
strip = true
opt-level = "s"
