[package]
name = "wasmcloud-example-provider-factorial"
version = "0.2.1"
edition = "2021"

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
futures = "0.3"
log = "0.4"
once_cell = "1.8"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls"] }
rmp-serde = "1.1.1"
serde_bytes = "0.11"
serde_json = "1.0"
serde = {version = "1.0.145", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.21", features = ["full"] }
toml = "0.5"
wasmbus-rpc = { version = "0.11.0", features = ["otel"] }
wasmcloud-interface-factorial = "0.7.0"

# test dependencies
[dev-dependencies]
wasmcloud-test-util = "0.6.0"

[[bin]]
name = "factorial"
path = "src/main.rs"
