# example/provider/factorial/Makefile

CAPABILITY_ID = wasmcloud:example:factorial
NAME = "Factorial"
VENDOR = "wasmcloud"
PROJECT = factorial
VERSION = 0.1.0
REVISION = 0

include ../../build/makefiles/provider.mk

