// This file is @generated by wasmcloud/weld-codegen 0.7.0.
// It is not intended for manual editing.
// namespace: org.wasmcloud.example.cron

#[allow(unused_imports)]
use async_trait::async_trait;
#[allow(unused_imports)]
use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use std::{borrow::Borrow, borrow::Cow, io::Write, string::ToString};
#[allow(unused_imports)]
use wasmbus_rpc::{
    cbor::*,
    common::{
        deserialize, message_format, serialize, Context, Message, MessageDispatch, MessageFormat,
        SendOpts, Transport,
    },
    error::{RpcError, RpcResult},
    Timestamp,
};

#[allow(dead_code)]
pub const SMITHY_VERSION: &str = "1.0";

/// The Cron service has a single method, timed_invoke, which
/// invokes an actor after a specified interval
/// wasmbus.contractId: wasmcloud:example:cron
/// wasmbus.actorReceive
#[async_trait]
pub trait Cron {
    /// returns the capability contract id for this interface
    fn contract_id() -> &'static str {
        "wasmcloud:example:cron"
    }
    /// Invoked on an actor on the interval specified in the link
    async fn timed_invoke(&self, ctx: &Context, arg: &u64) -> RpcResult<()>;
}

/// CronReceiver receives messages defined in the Cron service trait
/// The Cron service has a single method, timed_invoke, which
/// invokes an actor after a specified interval
#[doc(hidden)]
#[async_trait]
pub trait CronReceiver: MessageDispatch + Cron {
    async fn dispatch(&self, ctx: &Context, message: Message<'_>) -> Result<Vec<u8>, RpcError> {
        match message.method {
            "TimedInvoke" => {
                let value: u64 = wasmbus_rpc::common::deserialize(&message.arg)
                    .map_err(|e| RpcError::Deser(format!("'U64': {}", e)))?;

                let _resp = Cron::timed_invoke(self, ctx, &value).await?;
                let buf = Vec::new();
                Ok(buf)
            }
            _ => Err(RpcError::MethodNotHandled(format!(
                "Cron::{}",
                message.method
            ))),
        }
    }
}

/// CronSender sends messages to a Cron service
/// The Cron service has a single method, timed_invoke, which
/// invokes an actor after a specified interval
/// client for sending Cron messages
#[derive(Clone, Debug)]
pub struct CronSender<T: Transport> {
    transport: T,
}

impl<T: Transport> CronSender<T> {
    /// Constructs a CronSender with the specified transport
    pub fn via(transport: T) -> Self {
        Self { transport }
    }

    pub fn set_timeout(&self, interval: std::time::Duration) {
        self.transport.set_timeout(interval);
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl<'send> CronSender<wasmbus_rpc::provider::ProviderTransport<'send>> {
    /// Constructs a Sender using an actor's LinkDefinition,
    /// Uses the provider's HostBridge for rpc
    pub fn for_actor(ld: &'send wasmbus_rpc::core::LinkDefinition) -> Self {
        Self {
            transport: wasmbus_rpc::provider::ProviderTransport::new(ld, None),
        }
    }
}
#[cfg(target_arch = "wasm32")]
impl CronSender<wasmbus_rpc::actor::prelude::WasmHost> {
    /// Constructs a client for actor-to-actor messaging
    /// using the recipient actor's public key
    pub fn to_actor(actor_id: &str) -> Self {
        let transport =
            wasmbus_rpc::actor::prelude::WasmHost::to_actor(actor_id.to_string()).unwrap();
        Self { transport }
    }
}
#[async_trait]
impl<T: Transport + std::marker::Sync + std::marker::Send> Cron for CronSender<T> {
    #[allow(unused)]
    /// Invoked on an actor on the interval specified in the link
    async fn timed_invoke(&self, ctx: &Context, arg: &u64) -> RpcResult<()> {
        let buf = wasmbus_rpc::common::serialize(arg)?;

        let resp = self
            .transport
            .send(
                ctx,
                Message {
                    method: "Cron.TimedInvoke",
                    arg: Cow::Borrowed(&buf),
                },
                None,
            )
            .await?;
        Ok(())
    }
}
