# docker-compose.yml for PetClinic
#
# Start all the services.
# Before running this, secrets need to be created. The easiest thing to do
# is to use './run.sh all' to start all services.
#
# What's here:
#   wasmcloud host
#   local registry
#   postgres backend
#   pgadmin
#
# Ports open on localhost:
#  - 8080,443 httpserver to clinicapi (depending on whether tls is enabled)
#  - 4000 phoenix ui (washboard)
#  - 4222,6222,8000 nats
#  - 5000 registry
#  - 5432 postgres
#
# Data is not saved in volumes, to make it easier to start
#   with a clean image
#
version: '3.1'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      # must be on a port accessible to the capability provider
      - 127.0.0.1:5432:5432
    restart: always

  pgadmin:
    profiles:
      - localdev
    image: dpage/pgadmin4:5
    depends_on:
      - "db"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@example.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
    volumes:
      - $PWD/.pgadmin_init.json:/pgadmin4/servers.json
    ports:
      - 127.0.0.1:9999:80

  nats:
    image: nats:2.8.4-alpine
    ports:
      - "127.0.0.1:4222:4222"
      - "127.0.0.1:6222:6222"
      - "127.0.0.1:8222:8222"
    command: [ "-js" ]

  registry:
    profiles:
      - localdev
    image: registry:2.7
    ports:
      - "127.0.0.1:5000:5000"

  grafana:
    image: grafana/grafana:8.1.2
    ports:
      - 5050:3000
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    depends_on:
      - tempo  
  tempo:
    image: grafana/tempo:1.1.0
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - 8000:8000 # tempo
      - 55681:55681 # otlp http  

  wasmcloud:
    image: wasmcloud/wasmcloud_host:0.55.1
    depends_on: 
      - nats
    environment:
      LC_ALL: en_US.UTF-8
      RUST_LOG: debug,hyper=info
      WASMCLOUD_OCI_ALLOWED_INSECURE: registry:5000
      WASMCLOUD_RPC_HOST: nats
      WASMCLOUD_CTL_HOST: nats
      WASMCLOUD_PROV_RPC_HOST: nats
      WASMCLOUD_CLUSTER_SEED: ${WASMCLOUD_CLUSTER_SEED}
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:55681
      HOST_app: petclinic
    ports:
      - "127.0.0.1:4000:4000"  # washboard
      - "127.0.0.1:443:8443"   # httpserver HTTPS port
      - "127.0.0.1:8080:8080"

  # Services for wadm
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
  wadm:
    depends_on:
      - "nats"
      - "redis"
    image: wasmcloud.azurecr.io/wadm:0.1.0
    environment:
      - WADM_NATS_HOST=nats
      - WADM_REDIS_HOST=redis
