[[models]]
path = "."
files = [ "adsb.smithy" ]


[[models]]
url = "https://wasmcloud.github.io/interfaces/idl/org.wasmcloud"
files = [ "wasmcloud-core.smithy", "wasmcloud-model.smithy" ]

[tinygo]
output_dir = "."
formatter = [ "goimports", "-w" ]
files = [
    { path = "adsb-processor/adsb_gen.go", package="main", namespace = "org.jordanrash.adsb" },
    { path = "adsb-provider/adsb_gen.go", package="main", namespace = "org.jordanrash.adsb" },
]
