[package]
name = "customers"
version = "0.1.0"
authors = [ "" ]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]
name = "customers"

[dependencies]
async-trait = "0.1"
futures = "0.3"
form_urlencoded = "1.0"
regex = "1.5"
once_cell = "1.8"
serde_bytes = "0.11"
serde = {version = "1.0", features = ["derive"]}
wasmbus-rpc = "0.4.4"
petclinic-interface = { path = "../../petclinic-interface/rust"}
wasmcloud-interface-sqldb = "0.1.0"
wasmcloud-interface-numbergen = "0.1.8"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
