[package]
name = "adsbui"
version = "0.1.0"
authors = [ "wasmcloud Team" ]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
async-trait = "0.1.64"
form_urlencoded = "1.1.0"
futures = "0.3.26"
rust-embed = "6.4.2"
serde_bytes = "0.11.9"
serde_json = "1.0.92"
serde = { version = "1.0.152", features = ["derive"] }

wasmbus-rpc = "0.11.2"
wasmcloud-interface-httpserver = "0.9.0"
wasmcloud-interface-logging= "0.8.1"
mime_guess = "2.0.4"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
