CREATE TABLE IF NOT EXISTS todos (
    id VARCHAR(36) NOT NULL,
    url VARCHAR(42) NOT NULL,
    title VARCHAR(100) NOT NULL,
    priority INT4 NOT NULL DEFAULT 0,
    completed BOOL NOT NULL DEFAULT FALSE
);