# This is a full example of how to run the todo actor exposed with an HTTP server. Using this
# example requires you to have a Redis server running locally (though the linkdef can be modified to
# use a Redis server you have running elsewhere) and WADM running:
#
# https://github.com/wasmCloud/wadm/tree/main/wadm. You can deploy this example with a simple command:
#
# `wash app deploy wadm.yaml`

apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: todo
  annotations:
    version: v0.0.1
    description: "wasmCloud TODO API Example"
spec:
  components:
    - name: todo
      type: actor
      properties:
        image: wasmcloud.azurecr.io/todo:0.3.8
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: redis
            values:
              URL: redis://127.0.0.1:6379/
        - type: linkdef
          properties:
            target: httpserver
            values:
              ADDRESS: 0.0.0.0:8080

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.16.2
        contract: wasmcloud:httpserver
    - name: redis
      type: capability
      properties:
        image: wasmcloud.azurecr.io/kvredis:0.16.3
        contract: wasmcloud:keyvalue
