apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: pinger-ponger
  annotations:
    version: v0.0.1
    description: "wasmCloud pinger ponger example"
spec:
  components:
    - name: pinger
      type: actor
      properties:
        image: wasmcloud.azurecr.io/pinger:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1
        - type: linkdef
          properties:
            target: httpserver
            values:
              address: 0.0.0.0:8080
    - name: ponger
      type: actor
      properties:
        image: wasmcloud.azurecr.io/ponger:0.1.0
      traits:
        - type: spreadscaler
          properties:
            replicas: 1

    - name: httpserver
      type: capability
      properties:
        image: wasmcloud.azurecr.io/httpserver:0.17.0
        contract: wasmcloud:httpserver
