# codegen.toml

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces"
files = [ "core/wasmcloud-core.smithy", "core/wasmcloud-model.smithy", "httpserver/httpserver.smithy", "logging/logging.smithy", "blobstore/blobstore.smithy" ]

[rust]
output_dir = "gen"

[[rust.files]]
path = "blobstore.rs"
namespace = "org.wasmcloud.interface.blobstore"

[[rust.files]]
path = "httpserver.rs"
namespace = "org.wasmcloud.interface.httpserver"

[[rust.files]]
path = "logging.rs"
namespace = "org.wasmcloud.interface.logging"


