[package]
name = "verify"
version = "0.1.0"
description = "verify ed25519 signature"
keywords = [ "wasmcloud", "crypto", "ed25519" ]
authors = [ "wasmCloud team" ]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.21"
ed25519-compact = { version = "2", default-features = false, features = [ "x25519","pem", "ed25519" ] }
form_urlencoded = "1.0"
futures = "0.3"
serde = { version = "1", features = [ "derive" ] }
serde_json = "1.0"
wasmbus-rpc = "0.11"
wasmcloud-interface-httpserver = "0.9"
wasmcloud-interface-keyvalue = "0.9"
wasmcloud-interface-logging = { version = "0.8", features = [ "sync_macro" ] }
wasmcloud-interface-numbergen = "0.8"

[profile.release]
# Optimize for small code size
lto = true
opt-level = "s"
strip = true
