just := env_var_or_default("JUST", just_executable())
cargo := env_var_or_default("CARGO", "cargo")
wash := env_var_or_default("WASH", "wash")

_default:
    {{just}} --list

###############
# Development #
###############

build_target := env_var_or_defaulit("BUILD_TARGET", "wasm32-wasi")

# Format the source code
fmt:
    @{{cargo}} fmt

# Lint the source code
lint:
    @{{cargo}} clippy

# Build the source code
build:
    @{{cargo}} build --target {{build_target}}

# Build the source code continuously (requires cargo-watch)
build-watch:
    @{{cargo}} watch -- just build

# Build the source code for release
build-release:
    @{{cargo}} build --target {{build_target}} --release

#############
# Packaging #
#############

# Package the component as a wasmCloud actor
package-actor:
    @{{wash}} build
